# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Updater"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_packages_apps_Updater"

[[annotations]]
path = [".gitignore", "app/.gitignore", "keystore.properties.sample"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2023 Gradle, Inc."
SPDX-License-Identifier = "Apache-2.0"
